"""Adapter-generation tests — the multi-tool generators (`eeik generate-adapters`).

Each generator materialises a tool's config from a project manifest into files under the repo root
(`.kiro/`, `AGENTS.md`, `.cursor/rules/`, `GEMINI.md`). We redirect the module's ``REPO_ROOT`` to a
temp dir so the generators write there instead of the real repo, then assert the expected files exist,
carry the generated-by banner, and (for machine-readable outputs) parse cleanly. Dry-run must write
nothing.
"""

from __future__ import annotations

import importlib
import json

import pytest

adapters = importlib.import_module("eeik.adapters")


MANIFEST = {
    "project": {"name": "acme-orders", "domain": "banking", "project_type": "greenfield"},
    "technology": {
        "backend": {"language": "java", "version": "21", "framework": "spring-boot"},
        "frontend": {"framework": "angular", "version": "17"},
        "cloud": {"provider": "aws", "iac_tool": "cdk"},
        "database": {"primary": "postgres"},
    },
}


@pytest.fixture
def repo(tmp_path, monkeypatch):
    """Redirect the generators' output root to a temp dir (packs are still read from the real repo)."""
    monkeypatch.setattr(adapters, "REPO_ROOT", tmp_path)
    return tmp_path


# ── per-generator: files land where expected ────────────────────────────────────

def test_generate_kiro_writes_steering_hooks_and_settings(repo):
    adapters.generate_kiro(MANIFEST, dry=False)
    for rel in (
        ".kiro/steering/product.md",
        ".kiro/steering/tech.md",
        ".kiro/steering/structure.md",
        ".kiro/hooks/quality-hooks.json",
        ".kiro/settings.json",
    ):
        assert (repo / rel).is_file(), f"missing {rel}"
    # The steering file names the project and carries the do-not-edit banner.
    product = (repo / ".kiro/steering/product.md").read_text(encoding="utf-8")
    assert "acme-orders" in product
    assert "Generated by EEIK" in product


def _strip_jsonc(text: str) -> str:
    """Drop whole-line `//` comments — Kiro's settings.json is JSONC, not strict JSON."""
    return "\n".join(ln for ln in text.splitlines() if not ln.lstrip().startswith("//"))


def test_generate_kiro_emits_parseable_json(repo):
    adapters.generate_kiro(MANIFEST, dry=False)
    # hooks is strict JSON; settings is JSONC (a leading `// Generated by…` banner Kiro allows).
    json.loads((repo / ".kiro/hooks/quality-hooks.json").read_text(encoding="utf-8"))
    settings = json.loads(_strip_jsonc((repo / ".kiro/settings.json").read_text(encoding="utf-8")))
    assert "steeringFiles" in settings or "model" in settings


def test_generate_codex_writes_agents_md(repo):
    adapters.generate_codex(MANIFEST, dry=False)
    agents = repo / "AGENTS.md"
    assert agents.is_file()
    body = agents.read_text(encoding="utf-8")
    assert "acme-orders" in body
    assert "Generated by EEIK" in body


def test_generate_cursor_writes_three_rule_files(repo):
    adapters.generate_cursor(MANIFEST, dry=False)
    for rel in (
        ".cursor/rules/golden-rules.mdc",
        ".cursor/rules/architecture.mdc",
        ".cursor/rules/security.mdc",
    ):
        assert (repo / rel).is_file(), f"missing {rel}"


def test_generate_gemini_writes_gemini_md(repo):
    adapters.generate_gemini(MANIFEST, dry=False)
    gemini = repo / "GEMINI.md"
    assert gemini.is_file()
    assert "Generated by EEIK" in gemini.read_text(encoding="utf-8")


def test_generate_windsurf_writes_rule_files(repo):
    adapters.generate_windsurf(MANIFEST, dry=False)
    for rel in (".windsurf/rules/golden-rules.md", ".windsurf/rules/tech.md"):
        f = repo / rel
        assert f.is_file(), f"missing {rel}"
        assert "trigger: always_on" in f.read_text(encoding="utf-8")   # Windsurf rule frontmatter


def test_generate_cline_writes_rule_files(repo):
    adapters.generate_cline(MANIFEST, dry=False)
    for rel in (".clinerules/golden-rules.md", ".clinerules/project.md"):
        assert (repo / rel).is_file(), f"missing {rel}"
    assert "acme-orders" in (repo / ".clinerules/project.md").read_text(encoding="utf-8")


# ── dry-run writes nothing ──────────────────────────────────────────────────────

@pytest.mark.parametrize("generator", [
    "generate_kiro", "generate_codex", "generate_cursor", "generate_gemini",
    "generate_windsurf", "generate_cline",
])
def test_dry_run_writes_no_files(repo, generator):
    getattr(adapters, generator)(MANIFEST, dry=True)
    # No adapter artifacts should exist after a dry run.
    created = [p for p in repo.rglob("*") if p.is_file()]
    assert created == [], f"dry-run of {generator} wrote {created}"


# ── robustness: an empty manifest still generates without crashing ───────────────

def test_generators_tolerate_empty_manifest(repo):
    for generator in ("generate_kiro", "generate_codex", "generate_cursor", "generate_gemini"):
        getattr(adapters, generator)({}, dry=False)
    # Still produced the anchor files (generic defaults apply).
    assert (repo / "AGENTS.md").is_file()
    assert (repo / "GEMINI.md").is_file()
    assert (repo / ".kiro/settings.json").is_file()
    json.loads(_strip_jsonc((repo / ".kiro/settings.json").read_text(encoding="utf-8")))
