#!/usr/bin/env python3
"""
EEIK Adapter Generator
Generates AI tool adapter files from the shared capability-packs intelligence.

Adapters produced:
  .kiro/steering/    — Kiro (AWS IDE)
  .kiro/hooks/       — Kiro hooks
  AGENTS.md          — OpenAI Codex CLI
  .cursor/rules/     — Cursor IDE
  GEMINI.md          — Google Gemini CLI

Usage:
    eeik generate-adapters                     # dry-run
    eeik generate-adapters --apply             # write files
    eeik generate-adapters --apply --tools kiro,codex
    eeik generate-adapters --list              # show what would be generated
"""

import sys
import argparse
from pathlib import Path
from datetime import datetime

try:
    import yaml
except ImportError:
    print("ERROR: pyyaml required.  Run: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

REPO_ROOT  = Path(__file__).parent.parent
PACKS_DIR  = REPO_ROOT / "capability-packs"

ANSI_BOLD   = "\033[1m"
ANSI_GREEN  = "\033[92m"
ANSI_YELLOW = "\033[93m"
ANSI_CYAN   = "\033[96m"
ANSI_RESET  = "\033[0m"

GENERATED_BANNER = f"<!-- Generated by EEIK generate_adapters.py on {datetime.utcnow().strftime('%Y-%m-%d')} — do not edit by hand -->\n"
GENERATED_BANNER_YAML = f"# Generated by EEIK generate_adapters.py on {datetime.utcnow().strftime('%Y-%m-%d')} — do not edit by hand\n"


def load_manifest() -> dict:
    candidates = [
        REPO_ROOT / "project-manifest.yaml",
        REPO_ROOT / "bootstrap" / "manifests" / "project-manifest.yaml",
    ]
    for p in candidates:
        if p.exists():
            with open(p) as f:
                return yaml.safe_load(f) or {}
    return {}


def write_file(path: Path, content: str, dry: bool) -> None:
    if dry:
        print(f"  {ANSI_CYAN}Would write{ANSI_RESET}  {path.relative_to(REPO_ROOT)}  ({len(content)} chars)")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"  {ANSI_GREEN}Written{ANSI_RESET}     {path.relative_to(REPO_ROOT)}")


def read_golden_rules() -> str:
    """Load golden rules from core standards."""
    rules_file = PACKS_DIR / "core" / "standards" / "golden-rules.md"
    if rules_file.exists():
        return rules_file.read_text(encoding="utf-8")
    # Fallback condensed version
    return """## Golden Rules
1. Constructor injection only — no @Autowired on fields
2. No hardcoded secrets — use Secrets Manager or env vars
3. SLF4J not System.out — parameterised log messages
4. SOLID principles — Single Responsibility, Open/Closed, Liskov, ISP, DIP
5. Domain-Driven Design — respect bounded context boundaries
6. No SELECT * — always specify explicit column lists
7. Parameterised queries only — never build SQL via string concatenation
8. Conventional Commits — type(scope): description
9. No partial implementations — every method body is complete
10. jakarta.* in Spring Boot 3.x — never javax.*
11. No Thread.sleep() in tests — use Awaitility
12. No empty catch blocks — log at WARN/ERROR minimum
"""


def read_tech_summary(manifest: dict) -> str:
    tech = manifest.get("technology", {})
    lines = []
    b = tech.get("backend", {})
    if b.get("language"):
        lines.append(f"- Backend: {b['language']} {b.get('version','')} / {b.get('framework','')}")
    f = tech.get("frontend", {})
    if f.get("framework"):
        lines.append(f"- Frontend: {f['framework']} {f.get('version','')}")
    c = tech.get("cloud", {})
    if c.get("provider", "none") != "none":
        lines.append(f"- Cloud: {c['provider']} / IaC: {c.get('iac_tool','none')}")
    d = tech.get("database", {})
    if d.get("primary", "none") != "none":
        lines.append(f"- Database: {d['primary']}")
    return "\n".join(lines) if lines else "- (no manifest — generic enterprise defaults apply)"


# ── repository intelligence (projected into every adapter so each tool is substantive) ──────

def _read_yaml(path: Path) -> dict:
    try:
        return yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except (OSError, yaml.YAMLError):
        return {}


def _frontmatter(path: Path) -> dict:
    """Parse the leading YAML frontmatter (--- … ---) of an agent/standard file."""
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return {}
    # Tolerate an eeik-managed marker line before the frontmatter.
    if text.startswith("# eeik-managed"):
        text = text.split("\n", 1)[1] if "\n" in text else ""
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    return _read_yaml_str(text[3:end])


def _read_yaml_str(s: str) -> dict:
    try:
        return yaml.safe_load(s) or {}
    except yaml.YAMLError:
        return {}


def _first_sentence(text: str, limit: int = 140) -> str:
    one = " ".join(str(text).split())
    one = one.split(". ")[0].rstrip(".")
    return (one[:limit] + "…") if len(one) > limit else one


def read_pack_index() -> str:
    """A Markdown table of the capability packs available in this repo (name + focus)."""
    rows = []
    if PACKS_DIR.exists():
        for d in sorted(p for p in PACKS_DIR.iterdir() if p.is_dir()):
            meta = _read_yaml(d / "metadata.yaml")
            if not meta:
                continue
            rows.append(f"| `{d.name}` | {_first_sentence(meta.get('description', ''), 90)} |")
    if not rows:
        return "_(no capability packs found)_"
    return "| Pack | Focus |\n|---|---|\n" + "\n".join(rows)


def read_standards_index() -> str:
    """Comma-separated list of the standards materialised in `.claude/standards/`."""
    d = REPO_ROOT / ".claude" / "standards"
    files = sorted(f.stem for f in d.glob("*.md")) if d.exists() else []
    return ", ".join(f"`{s}`" for s in files) if files else "_(none)_"


def read_agent_index(limit: int | None = None) -> str:
    """A Markdown table of the specialist agents (name + trigger) from `.claude/agents/`."""
    d = REPO_ROOT / ".claude" / "agents"
    if not d.exists():
        return "_(no agents found)_"
    rows = []
    for f in sorted(d.glob("*.md")):
        fm = _frontmatter(f)
        name = fm.get("name") or f.stem
        desc = _first_sentence(fm.get("description", ""), 110)
        if desc:
            rows.append(f"| `{name}` | {desc} |")
    if limit:
        rows = rows[:limit]
    if not rows:
        return "_(no agents found)_"
    return "| Agent | Use for |\n|---|---|\n" + "\n".join(rows)


def read_patterns_index() -> str:
    """Bulleted list of approved patterns in `knowledge/patterns/`."""
    d = REPO_ROOT / "knowledge" / "patterns"
    if not d.exists():
        return "_(none)_"
    items = [f"- `{f.stem}`" for f in sorted(d.glob("*.md")) if f.name.lower() != "readme.md"]
    return "\n".join(items) if items else "_(none)_"


def capability_context() -> str:
    """A rich, tool-agnostic 'what this repo gives you' block (packs + standards + patterns)."""
    return f"""## Capability packs (engineering intelligence available)

{read_pack_index()}

Activate the packs your `project-manifest.yaml` selects with `eeik activate --apply`; each materialises
its agents and standards into `.claude/`.

## Standards enforced

{read_standards_index()}

Standards live in `.claude/standards/` (and `capability-packs/<pack>/standards/`). They define the
CORRECT/WRONG patterns the golden rules summarise.

## Approved patterns

{read_patterns_index()}

See `knowledge/patterns/` for the full write-ups and `knowledge/anti-patterns/` for what to avoid."""


# ── Kiro ──────────────────────────────────────────────────────────────────────

def generate_kiro(manifest: dict, dry: bool) -> None:
    print(f"\n{ANSI_BOLD}Kiro (.kiro/){ANSI_RESET}")
    project = manifest.get("project", {})
    name    = project.get("name", "this project")
    tech_summary = read_tech_summary(manifest)
    golden       = read_golden_rules()

    # steering/product.md
    product_md = f"""{GENERATED_BANNER}# Product Steering — {name}

> Kiro injects this file into every interaction as persistent context.
> Keep it current. It is the source of truth for what this product is.

## What This Is

{project.get('description', f'Enterprise application: {name}')}

- **Project type**: {project.get('type', 'greenfield')}
- **Domain**: {project.get('domain', 'generic')}
- **Environments**: {', '.join(project.get('environments', ['dev', 'staging', 'prod']))}

## Team Context

This project uses the **EEIK bootstrap** configuration stack:
- Claude Code agents in `.claude/agents/`
- Capability packs in `capability-packs/`
- Shared knowledge in `knowledge/`

## Business Rules

Consult `knowledge/business-rules/` for domain-specific rules.
Consult `.claude/memory/domain-glossary.md` for terminology.
"""

    # steering/tech.md
    tech_md = f"""{GENERATED_BANNER}# Technology Steering — {name}

> Always-on technology context for Kiro. Keep aligned with project-manifest.yaml.

## Stack

{tech_summary}

## Governance

- Profile: {manifest.get('governance', {}).get('profile', 'standard')}
- Branch strategy: {manifest.get('governance', {}).get('branch_strategy', 'github-flow')}
- Coverage threshold: {manifest.get('governance', {}).get('coverage_threshold', 80)}%

## Non-Negotiable Rules

{golden}

{capability_context()}
"""

    # steering/structure.md
    structure_md = f"""{GENERATED_BANNER}# Structure Steering — {name}

> Repository layout and architecture patterns. Kiro reads this on every task.

## Repository Layout

```
.claude/          Claude Code agents, commands, hooks, memory
.kiro/            Kiro steering and hooks (this directory)
.github/          Copilot instructions + CI/CD workflows
capability-packs/ Intelligence packs (agents, standards, workflows)
knowledge/        ADRs, patterns, anti-patterns, incidents
generators/       Manifest-driven generators
eeik/            Engine package (validate, activate, generate-adapters, lock)
templates/        Code templates per technology
```

## Architecture Pattern

- **Hexagonal Architecture** — domain / application / infrastructure / web layers
- **Domain-Driven Design** — bounded contexts, aggregates, domain events
- Dependencies always flow inward (domain has zero outward dependencies)

## Specialist agents

Route each task to the right specialist (`.claude/agents/`):

{read_agent_index()}

## Package Structure (Java)

```
com.{name.lower().replace('-','.')}/
  domain/         Entities, value objects, domain events, ports
  application/    Use cases, command/query handlers
  infrastructure/ JPA repos, messaging adapters, external clients
  web/            REST controllers, request/response DTOs
```

## Before Writing Code

1. Identify bounded context and layer
2. Check `knowledge/patterns/` for existing patterns
3. Check `knowledge/anti-patterns/` for what NOT to do
4. Follow the Golden Rules in `.kiro/steering/tech.md`
"""

    write_file(REPO_ROOT / ".kiro" / "steering" / "product.md",   product_md,   dry)
    write_file(REPO_ROOT / ".kiro" / "steering" / "tech.md",      tech_md,      dry)
    write_file(REPO_ROOT / ".kiro" / "steering" / "structure.md", structure_md, dry)

    # hooks/format-on-save.json
    hooks_json = """{
  "hooks": [
    {
      "name": "post-edit-quality-check",
      "event": "file:saved",
      "matchPattern": "**/*.java",
      "command": "bash .claude/hooks/post-edit-check.sh",
      "description": "Run EEIK quality checks after Java file save"
    },
    {
      "name": "post-edit-ts-check",
      "event": "file:saved",
      "matchPattern": "**/*.ts",
      "command": "bash .claude/hooks/post-edit-check.sh",
      "description": "Run EEIK quality checks after TypeScript file save"
    }
  ]
}
"""
    write_file(REPO_ROOT / ".kiro" / "hooks" / "quality-hooks.json", hooks_json, dry)

    # .kiro/settings.json
    settings_json = f"""{GENERATED_BANNER_YAML.replace('# Generated', '// Generated')}{{
  "model": "claude-sonnet-4-6",
  "steeringFiles": [
    ".kiro/steering/product.md",
    ".kiro/steering/tech.md",
    ".kiro/steering/structure.md"
  ],
  "specsDirectory": ".kiro/specs",
  "hooksDirectory": ".kiro/hooks"
}}
"""
    write_file(REPO_ROOT / ".kiro" / "settings.json", settings_json, dry)


# ── Codex CLI (AGENTS.md) ─────────────────────────────────────────────────────

def generate_codex(manifest: dict, dry: bool) -> None:
    print(f"\n{ANSI_BOLD}Codex CLI (AGENTS.md){ANSI_RESET}")
    project      = manifest.get("project", {})
    name         = project.get("name", "this project")
    tech_summary = read_tech_summary(manifest)
    golden       = read_golden_rules()

    agents_md = f"""{GENERATED_BANNER}# AGENTS.md — {name}

OpenAI Codex CLI reads this file to understand the repository context.
Child AGENTS.md files in subdirectories override or extend these instructions.

---

## Project

{project.get('description', f'Enterprise application: {name}')}

- Type: {project.get('type', 'greenfield')}
- Domain: {project.get('domain', 'generic')}
- Governance profile: {manifest.get('governance', {}).get('profile', 'standard')}

## Technology Stack

{tech_summary}

---

## Non-Negotiable Coding Rules

{golden}

---

{capability_context()}

---

## Specialist agents

Route work to the right specialist (guidance lives in `.claude/agents/`):

{read_agent_index()}

---

## Repository Layout

```
.claude/          Claude Code configuration (agents, commands, hooks)
capability-packs/ Intelligence packs — read these for standards
knowledge/        Patterns, anti-patterns, ADRs, lessons learned
generators/       Project generators
eeik/            Engine: validate, activate, generate-adapters, lock
templates/        Code templates
```

## Before Writing Code

1. Read `capability-packs/core/standards/golden-rules.md`
2. Check `knowledge/patterns/` for existing patterns
3. Check `knowledge/anti-patterns/` for what to avoid
4. Identify the bounded context (domain, application, infrastructure, web)
5. State acceptance criteria before generating

## Commit Message Format

All commits must follow Conventional Commits:
```
type(scope): description

Types: feat | fix | refactor | test | docs | chore | ci | perf | security
```

## Test Requirements

- Unit tests for all domain logic
- Integration tests for all repository/adapter classes
- No `Thread.sleep()` — use Awaitility
- No `Optional.get()` without guard — use `orElseThrow()`

---

## Sub-directory Context

- `src/main/java/` → Java/Spring Boot source. See `capability-packs/java/`
- `src/test/`      → Tests. See `capability-packs/java/standards/`
- `infrastructure/`→ CDK/Terraform IaC. See `capability-packs/aws/`
- `frontend/`      → Angular/React. See relevant capability pack
"""

    write_file(REPO_ROOT / "AGENTS.md", agents_md, dry)


# ── Cursor ────────────────────────────────────────────────────────────────────

def generate_cursor(manifest: dict, dry: bool) -> None:
    print(f"\n{ANSI_BOLD}Cursor (.cursor/rules/){ANSI_RESET}")
    golden = read_golden_rules()

    # golden-rules.mdc
    golden_mdc = f"""---
description: EEIK Golden Rules — apply to ALL code in ALL files
globs: ["**/*.java", "**/*.ts", "**/*.py", "**/*.kt"]
alwaysApply: true
---
{GENERATED_BANNER}
{golden}

## Enforcement

These rules are BLOCKERS in code review. No exceptions.
Full standards: `capability-packs/core/standards/golden-rules.md`
"""
    write_file(REPO_ROOT / ".cursor" / "rules" / "golden-rules.mdc", golden_mdc, dry)

    # architecture.mdc
    arch_mdc = f"""---
description: EEIK Architecture Rules — hexagonal architecture and DDD
globs: ["**/*.java", "**/*.ts"]
alwaysApply: true
---
{GENERATED_BANNER}
## Hexagonal Architecture

Package structure (Java):
```
domain/         — Entities, value objects, domain events, ports (interfaces)
application/    — Use cases, command/query handlers
infrastructure/ — JPA repos, messaging, external clients
web/            — REST controllers, DTOs
```

Dependencies flow INWARD only:
- infrastructure → application → domain
- web → application
- domain has ZERO dependencies on other layers

## DDD Rules

- Aggregates enforce invariants — no direct field access from outside
- Domain events for cross-context communication — never direct DB joins across contexts
- Value objects are immutable
- Repositories return domain objects, not JPA entities

## Knowledge Base

- Patterns: `knowledge/patterns/`
- Anti-patterns: `knowledge/anti-patterns/`
- Reference architectures: `knowledge/reference-architectures/`
"""
    write_file(REPO_ROOT / ".cursor" / "rules" / "architecture.mdc", arch_mdc, dry)

    # security.mdc
    security_mdc = f"""---
description: EEIK Security Rules — apply to all files
globs: ["**/*"]
alwaysApply: true
---
{GENERATED_BANNER}
## Security Non-Negotiables

- NEVER hardcode credentials, API keys, passwords, or AWS account IDs
- ALL secrets go to AWS Secrets Manager / environment variables
- NEVER log sensitive data (PII, tokens, passwords)
- SQL must use parameterised queries only — never string concatenation
- Input validation on ALL public API endpoints
- Dependency versions must be explicit — no `latest` or `*`

## OWASP Top 10 Checklist

Before any PR touching auth, data access, or external input:
- [ ] Injection — parameterised queries, no string-built SQL
- [ ] Broken Auth — JWT validation, session management
- [ ] Sensitive Data Exposure — encryption at rest and in transit
- [ ] Security Misconfiguration — no default passwords, no stack traces in responses
- [ ] XSS — input sanitisation for any HTML output

Full standard: `capability-packs/core/standards/security-baseline.md`
"""
    write_file(REPO_ROOT / ".cursor" / "rules" / "security.mdc", security_mdc, dry)

    # capabilities.mdc — the engineering intelligence available (packs, standards, agents)
    capabilities_mdc = f"""---
description: EEIK Capabilities — packs, standards, and specialist agents available in this repo
globs: ["**/*"]
alwaysApply: false
---
{GENERATED_BANNER}
{capability_context()}

## Specialist agents

{read_agent_index()}
"""
    write_file(REPO_ROOT / ".cursor" / "rules" / "capabilities.mdc", capabilities_mdc, dry)


# ── Gemini CLI ────────────────────────────────────────────────────────────────

def generate_gemini(manifest: dict, dry: bool) -> None:
    print(f"\n{ANSI_BOLD}Gemini CLI (GEMINI.md){ANSI_RESET}")
    project      = manifest.get("project", {})
    name         = project.get("name", "this project")
    tech_summary = read_tech_summary(manifest)
    golden       = read_golden_rules()

    gemini_md = f"""{GENERATED_BANNER}# GEMINI.md — {name}

Google Gemini CLI reads this file as persistent project context.

---

## Project Overview

{project.get('description', f'Enterprise application: {name}')}

**Type**: {project.get('type', 'greenfield')} | **Domain**: {project.get('domain', 'generic')} | **Profile**: {manifest.get('governance', {}).get('profile', 'standard')}

## Technology

{tech_summary}

---

## Coding Standards

{golden}

---

## Repository Intelligence

This repository uses **EEIK (Enterprise Engineering Intelligence Kit)**.
Context is structured across:

| Location | Contents |
|----------|----------|
| `capability-packs/` | Standards, agents, workflows per technology |
| `knowledge/patterns/` | Approved implementation patterns with code examples |
| `knowledge/anti-patterns/` | What NOT to do and why |
| `knowledge/adr-repository/` | Architecture Decision Records |
| `.claude/memory/` | Project-specific context, constraints, decisions |

{capability_context()}

## Specialist agents

{read_agent_index()}

## Architecture

Hexagonal Architecture + DDD:
- `domain/` — pure business logic, no framework dependencies
- `application/` — use cases and orchestration
- `infrastructure/` — adapters for DB, messaging, external services
- `web/` — HTTP layer, DTOs

## Key Commands

```bash
# Validate manifest
eeik validate

# Check active packs and adapter status
eeik status

# Regenerate adapters after manifest change
eeik generate-adapters --apply
```
"""
    write_file(REPO_ROOT / "GEMINI.md", gemini_md, dry)


# ── Windsurf (Codeium) ──────────────────────────────────────────────────────────

def generate_windsurf(manifest: dict, dry: bool) -> None:
    print(f"\n{ANSI_BOLD}Windsurf (.windsurf/rules/){ANSI_RESET}")
    project      = manifest.get("project", {})
    name         = project.get("name", "this project")
    tech_summary = read_tech_summary(manifest)
    golden       = read_golden_rules()

    # Windsurf reads every file under .windsurf/rules/ as always-on workspace rules (Cascade).
    golden_md = f"""{GENERATED_BANNER}---
trigger: always_on
---

# Golden Rules — {name}

Non-negotiable engineering standards. Apply to all generated and edited code.

{golden}
"""
    write_file(REPO_ROOT / ".windsurf" / "rules" / "golden-rules.md", golden_md, dry)

    tech_md = f"""{GENERATED_BANNER}---
trigger: always_on
---

# Technology & Architecture — {name}

**Type**: {project.get('project_type', 'greenfield')} | **Domain**: {project.get('domain', 'generic')} | **Profile**: {manifest.get('governance', {}).get('profile', 'standard')}

## Stack

{tech_summary}

## Architecture (hexagonal + DDD)

- `domain/` — pure business logic, no framework dependencies
- `application/` — use cases and orchestration
- `infrastructure/` — adapters for DB, messaging, external services
- `web/` — HTTP layer, DTOs

## Repository intelligence

This repository uses **EEIK**. Regenerate this file with `eeik generate-adapters --apply` after a
manifest change.

{capability_context()}

## Specialist agents

{read_agent_index()}
"""
    write_file(REPO_ROOT / ".windsurf" / "rules" / "tech.md", tech_md, dry)


# ── Cline ───────────────────────────────────────────────────────────────────────

def generate_cline(manifest: dict, dry: bool) -> None:
    print(f"\n{ANSI_BOLD}Cline (.clinerules/){ANSI_RESET}")
    project      = manifest.get("project", {})
    name         = project.get("name", "this project")
    tech_summary = read_tech_summary(manifest)
    golden       = read_golden_rules()

    # Cline reads every Markdown file in .clinerules/ as persistent instructions for the workspace.
    golden_md = f"""{GENERATED_BANNER}# Golden Rules — {name}

Non-negotiable engineering standards. Apply to all code Cline writes or edits.

{golden}
"""
    write_file(REPO_ROOT / ".clinerules" / "golden-rules.md", golden_md, dry)

    project_md = f"""{GENERATED_BANNER}# Project — {name}

{project.get('description', f'Enterprise application: {name}')}

**Type**: {project.get('project_type', 'greenfield')} | **Domain**: {project.get('domain', 'generic')} | **Profile**: {manifest.get('governance', {}).get('profile', 'standard')}

## Technology

{tech_summary}

## Architecture (hexagonal + DDD)

- `domain/` — pure business logic, no framework dependencies
- `application/` — use cases and orchestration
- `infrastructure/` — adapters for DB, messaging, external services
- `web/` — HTTP layer, DTOs

## Repository intelligence

This repository uses **EEIK**. Regenerate with `eeik generate-adapters --apply`.

{capability_context()}

## Specialist agents

{read_agent_index()}
"""
    write_file(REPO_ROOT / ".clinerules" / "project.md", project_md, dry)


# ── main ──────────────────────────────────────────────────────────────────────

ALL_TOOLS = ["kiro", "codex", "cursor", "gemini", "windsurf", "cline"]

GENERATORS = {
    "kiro":     generate_kiro,
    "codex":    generate_codex,
    "cursor":   generate_cursor,
    "gemini":   generate_gemini,
    "windsurf": generate_windsurf,
    "cline":    generate_cline,
}


def main() -> int:
    parser = argparse.ArgumentParser(description="EEIK Adapter Generator")
    parser.add_argument("--apply",  action="store_true", help="Write files (default: dry-run)")
    parser.add_argument("--tools",  default=",".join(ALL_TOOLS),
                        help=f"Comma-separated tools to generate (default: all). Options: {','.join(ALL_TOOLS)}")
    parser.add_argument("--list",   action="store_true", help="List adapters and exit")
    args = parser.parse_args()

    dry   = not args.apply
    tools = [t.strip() for t in args.tools.split(",") if t.strip()]

    print(f"\n{ANSI_BOLD}EEIK Adapter Generator{ANSI_RESET}")
    print(f"  Mode  : {'dry-run (pass --apply to write)' if dry else 'APPLY'}")
    print(f"  Tools : {', '.join(tools)}\n")

    if args.list:
        for t in ALL_TOOLS:
            print(f"  {'✓' if t in tools else '—'} {t}")
        return 0

    manifest = load_manifest()
    if not manifest:
        print(f"{ANSI_YELLOW}⚠ No project-manifest.yaml found — generating with generic defaults{ANSI_RESET}")

    for tool in tools:
        if tool not in GENERATORS:
            print(f"\n{ANSI_YELLOW}⚠ Unknown tool '{tool}' — skipping{ANSI_RESET}")
            continue
        GENERATORS[tool](manifest, dry)

    print(f"\n{ANSI_BOLD}Done.{ANSI_RESET}")
    if dry:
        print("  Pass --apply to write files.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
